singleQuote: true
semi: false
printWidth: 100
arrowParens: 'always'
bracketSpacing: true
embeddedLanguageFormatting: 'auto'
endOfLine: 'lf'
htmlWhitespaceSensitivity: 'css'
insertPragma: false
jsxBracketSameLine: false
jsxSingleQuote: false
proseWrap: 'preserve'
quoteProps: 'as-needed'
requirePragma: false
tabWidth: 2
trailingComma: 'all'
useTabs: false
